sudo: true
language: generic

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

matrix:
  include:
    - env: GHCVER=8.2.2
      addons: {apt: {packages: [ghc-8.2.2,cabal-install-2.4], sources: [hvr-ghc]}}
    - env: GHCVER=8.4.3
      addons: {apt: {packages: [ghc-8.4.3,cabal-install-2.4], sources: [hvr-ghc]}}
    - env: GHCVER=8.6.1
      addons: {apt: {packages: [ghc-8.6.1,cabal-install-2.4], sources: [hvr-ghc]}}
    - env: GHCVER=8.8.1
      addons: {apt: {packages: [ghc-8.8.1,cabal-install-2.4], sources: [hvr-ghc]}}

install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/2.4/bin:$PATH
 - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
 - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install rethinkdb -y
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests

before_script:
 - sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/default.conf
 - sudo /etc/init.d/rethinkdb restart

script:
 - cabal configure --enable-tests
 - cabal build
 - cabal test
